import SWRConfigContext from '@/context/SWRConfigContext';
import { MSWComponent } from '@/mocks/MSWComponent';
import type { Metadata } from 'next';
import { GlobalStyle } from '../styles/global-style';

export const metadata: Metadata = {
  title: '캠핑갈까',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <GlobalStyle />
      <body>
        <MSWComponent>
          <SWRConfigContext>{children}</SWRConfigContext>
        </MSWComponent>
      </body>
    </html>
  );
}
