import SWRConfigContext from '@/context/SWRConfigContext';
import { MSWComponent } from '@/mocks/MSWComponent';
import type { Metadata } from 'next';
import { GlobalStyle } from '../styles/global-style';
import RecoilRootProvider from '@/Provider/RecoilRootProvider';

export const metadata: Metadata = {
  title: '캠핑갈까',
  description: 'Generated by create next app',
};

declare global {
  interface Window {
    naver: any;
  }
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <GlobalStyle />
      <head>
        {/* <script
          type="text/javascript"
          src="https://static.nid.naver.com/js/naveridlogin_js_sdk_2.0.0.js"
          charSet="utf-8"
        ></script> */}
      </head>
      <body>
        <RecoilRootProvider>
          <MSWComponent>
            <SWRConfigContext>{children}</SWRConfigContext>
          </MSWComponent>
        </RecoilRootProvider>
      </body>
    </html>
  );
}
